<?php
session_start();
require_once 'includes/config.php';
$isAdmin = !empty($_SESSION['alogin']);
$email = $_SESSION['login'] ?? '';
$bookingId = (int)($_GET['booking'] ?? 0);
if ($bookingId < 1 || (!$isAdmin && $email === '')) { header('Location: index.php'); exit; }
$sql = 'SELECT b.*, u.FullName, u.EmailId, u.Address, u.City, u.Country, u.ContactNo, v.VehiclesTitle, v.PricePerDay, br.BrandName FROM tblbooking b JOIN tblusers u ON u.EmailId=b.userEmail JOIN tblvehicles v ON v.id=b.VehicleId JOIN tblbrands br ON br.id=v.VehiclesBrand WHERE b.id=:id';
if (!$isAdmin) $sql .= ' AND b.userEmail=:email';
$q=$dbh->prepare($sql); $params=[':id'=>$bookingId]; if (!$isAdmin) $params[':email']=$email; $q->execute($params); $b=$q->fetch(PDO::FETCH_ASSOC);
if (!$b) { http_response_code(404); exit('Invoice not found.'); }
$settings=$dbh->query('SELECT * FROM tblinvoicesettings WHERE id=1')->fetch(PDO::FETCH_ASSOC) ?: [];
$from=new DateTime($b['FromDate']); $to=new DateTime($b['ToDate']); $days=max(1,$from->diff($to)->days+1); $total=$days*(float)$b['PricePerDay'];
$invoiceNo=htmlentities(($settings['InvoicePrefix'] ?? 'CR').'-'.date('Y').'-'.str_pad((string)$bookingId,5,'0',STR_PAD_LEFT));
if (isset($_GET['download'])) header('Content-Disposition: attachment; filename="Invoice-'.$bookingId.'.html"');
?>
<!doctype html><html><head><meta charset="utf-8"><title>Invoice <?= $invoiceNo ?></title><style>body{background:#eef2f7;font:14px Arial;color:#172033}.invoice{max-width:850px;margin:30px auto;background:#fff;padding:42px;box-shadow:0 3px 18px #ccd3df}.head,.grid{display:flex;justify-content:space-between;gap:24px}.box{border:1px solid #dbe3ef;padding:14px;flex:1}.meta{width:100%;border-collapse:collapse;margin:20px 0}.meta th,.meta td{border:1px solid #dbe3ef;padding:12px}.meta th{background:#eff6ff}.actions{text-align:right}.popup{background:#1d4ed8;color:#fff;padding:25px;text-align:center;font-size:25px;font-weight:bold}.popup small{font-size:14px}.total{text-align:right;font-size:20px;font-weight:bold}@media print{.actions,.popup{display:none}body{background:#fff}.invoice{box-shadow:none;margin:0}}</style></head><body><?php if(isset($_GET['placed'])){?><div class="popup">ORDER PLACED SUCCESSFULLY<br><small>Your booking is confirmed and invoice is ready.</small></div><?php }?><main class="invoice"><div class="actions"><a href="index.php">Back to Home</a> &nbsp; <a href="?booking=<?=$bookingId?>&download=1">Download invoice</a> &nbsp; <button onclick="print()">Print / Save PDF</button></div><div class="head"><div><h1><?=htmlentities($settings['CompanyName']??'Car Rental Portal')?></h1><p><?=nl2br(htmlentities($settings['Address']??''))?></p></div><div><b>TAX INVOICE</b><br>Invoice: <?=$invoiceNo?><br>Cash payment</div></div><div class="grid"><div class="box"><h3>Billed to</h3><b><?=htmlentities($b['FullName'])?></b><br><?=nl2br(htmlentities($b['BillingAddress']??$b['Address']))?><br><?=htmlentities($b['EmailId'])?><br><?=htmlentities($b['BillingPhone']??$b['ContactNo'])?></div><div class="box"><h3>Shipped to</h3><b><?=htmlentities($b['FullName'])?></b><br><?=nl2br(htmlentities($b['ShippingAddress']??$b['Address']))?><br><?=htmlentities($b['EmailId'])?><br><?=htmlentities($b['ShippingPhone']??$b['ContactNo'])?></div></div><table class="meta"><tr><th>Vehicle</th><th>Rate/day</th><th>Days</th><th>Amount</th></tr><tr><td><?=htmlentities($b['BrandName'].' '.$b['VehiclesTitle'])?></td><td>₹<?=number_format($b['PricePerDay'],0)?></td><td><?=$days?></td><td>₹<?=number_format($total,0)?></td></tr></table><p class="total">Grand Total: ₹<?=number_format($total,0)?></p><p>Payment due in cash at vehicle collection.</p></main></body></html>
